import { initializeApp } from "https://www.gstatic.com/firebasejs/10.13.0/firebase-app.js";
import { getFirestore, collection, addDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.13.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyCIk8rFLqO8diN8klO9V3NwnSra6pV_WO0",authDomain:"painel-administrativo-aaf11.firebaseapp.com",projectId:"painel-administrativo-aaf11",storageBucket:"painel-administrativo-aaf11.firebasestorage.app",messagingSenderId:"27717286344",appId:"1:27717286344:web:60899ccb213c565056e8fd"};
const app=initializeApp(firebaseConfig);const db=getFirestore(app);
function money(v){return Number(v)||0}
function parsePrice(text){if(!text)return null;const m=String(text).replace(/\./g,'').replace(',','.').match(/\d+(?:\.\d+)?/);return m?Number(m[0]):null}
function clean(s){return String(s||'').replace(/<[^>]*>/g,'').trim()}
function today(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
async function saveOrder(data){try{await addDoc(collection(db,'pedidos'),{...data,status:'pendente',origem:'Site',dataLocal:today(),criadoEm:serverTimestamp()});return true}catch(e){console.error('Registro do pedido:',e);return false}}
function cardItemFromLink(link){const card=link.closest('.product-card');const name=clean(card?.querySelector('h3')?.textContent||link.dataset.produto||'Produto');const price=parsePrice(card?.querySelector('.price')?.textContent||'');return {nome:name,preco:price,quantidade:1}}

// Pedido direto pelo botão WhatsApp: registra o pedido antes de abrir o WhatsApp.
document.addEventListener('click',async e=>{const link=e.target.closest('.btn-whats');if(!link)return;if(link.id==='ckSubmit')return;e.preventDefault();if(link.dataset.tlOrderBusy==='1')return;link.dataset.tlOrderBusy='1';const item=cardItemFromLink(link);await saveOrder({clienteNome:'Cliente do site',itens:[item],total:item.preco==null?0:item.preco,produto:item.nome});window.open(link.href,'_blank','noopener');link.dataset.tlOrderBusy='0'},true);

// Checkout do carrinho: captura os dados de entrega e todos os itens.
document.addEventListener('click',async e=>{const btn=e.target.closest('#ckSubmit');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();if(btn.dataset.tlOrderBusy==='1')return;btn.dataset.tlOrderBusy='1';const get=id=>document.getElementById(id)?.value?.trim()||'';const name=get('ckName'),city=get('ckCity'),otherCity=get('ckOtherCity'),neighborhood=get('ckNeighborhood'),street=get('ckStreet'),number=get('ckNumber'),ref=get('ckRef');const cityFinal=city==='Outra'?otherCity:city;const raw=localStorage.getItem('tl_cart_v1');let cart={};try{cart=JSON.parse(raw)||{}}catch(_){}const itens=Object.values(cart).map(i=>({nome:i.name||'Produto',preco:i.price==null?null:Number(i.price),quantidade:1}));const total=itens.reduce((s,i)=>s+(i.preco==null?0:i.preco*(i.quantidade||1)),0);if(!name||!cityFinal||!street||!number){btn.dataset.tlOrderBusy='0';return}await saveOrder({cliente:{nome:name,cidade:cityFinal,bairro:neighborhood,rua:street,numero:number,referencia:ref},clienteNome:name,itens,total,produto:itens.map(i=>i.nome).join(', ')});const lines=['Olá! Vim do site da Théo Lorenzo Multimarcas TL e quero fazer esse pedido:',''];itens.forEach(i=>lines.push('- '+i.nome+' - '+(i.preco==null?'a combinar':'R$ '+i.preco.toFixed(2).replace('.',','))));lines.push('','Total: R$ '+total.toFixed(2).replace('.',','),'','Dados para entrega:','Nome: '+name,'Cidade: '+cityFinal,neighborhood?'Bairro: '+neighborhood:'','Rua: '+street+', nº '+number,ref?'Referência: '+ref:'');window.open('https://wa.me/558681942709?text='+encodeURIComponent(lines.filter(Boolean).join('\n')),'_blank','noopener');btn.dataset.tlOrderBusy='0'},true);
